# ============================================================================
# Hedera Guardian Setup Script for Carbon Passport Platform
# ============================================================================
# Prerequisites: Docker Desktop, Git
# 
# This script:
# 1. Clones the Guardian repository
# 2. Configures it with your Hedera testnet credentials
# 3. Starts all Guardian services via Docker Compose
# 4. Waits for Guardian to be ready
# 5. Creates the default users (StandardRegistry, VVB, ProjectProponent)
# ============================================================================

$ErrorActionPreference = "Stop"

# --- Configuration ---
$GUARDIAN_DIR = "$PSScriptRoot\..\guardian"
$GUARDIAN_REPO = "https://github.com/hashgraph/guardian.git"
$GUARDIAN_BRANCH = "main"

# Read Hedera credentials from .env.local
$envFile = "$PSScriptRoot\..\.env.local"
if (!(Test-Path $envFile)) {
    Write-Error ".env.local not found. Create it with HEDERA_OPERATOR_ID and HEDERA_OPERATOR_KEY."
    exit 1
}

$envContent = Get-Content $envFile
$OPERATOR_ID = ($envContent | Where-Object { $_ -match "^HEDERA_OPERATOR_ID=" }) -replace "HEDERA_OPERATOR_ID=", ""
$OPERATOR_KEY = ($envContent | Where-Object { $_ -match "^HEDERA_OPERATOR_KEY=" }) -replace "HEDERA_OPERATOR_KEY=", ""
$NETWORK = ($envContent | Where-Object { $_ -match "^HEDERA_NETWORK=" }) -replace "HEDERA_NETWORK=", ""

if (!$OPERATOR_ID -or !$OPERATOR_KEY) {
    Write-Error "HEDERA_OPERATOR_ID and HEDERA_OPERATOR_KEY must be set in .env.local"
    exit 1
}
if (!$NETWORK) { $NETWORK = "testnet" }

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Hedera Guardian Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Operator ID : $OPERATOR_ID"
Write-Host "  Network     : $NETWORK"
Write-Host "  Guardian Dir: $GUARDIAN_DIR"
Write-Host ""


# --- Step 1: Check Docker ---
Write-Host "[1/6] Checking Docker..." -ForegroundColor Yellow
try {
    $dockerVersion = docker --version 2>&1
    Write-Host "  Docker found: $dockerVersion" -ForegroundColor Green
} catch {
    Write-Error @"
Docker is not installed or not in PATH.

Install Docker Desktop from: https://www.docker.com/products/docker-desktop/
After installing, make sure Docker Desktop is running before re-running this script.
"@
    exit 1
}

# Verify Docker is running
try {
    docker info 2>&1 | Out-Null
    Write-Host "  Docker daemon is running." -ForegroundColor Green
} catch {
    Write-Error "Docker is installed but not running. Start Docker Desktop first."
    exit 1
}

# --- Step 2: Clone Guardian ---
Write-Host "[2/6] Cloning Guardian repository..." -ForegroundColor Yellow
if (Test-Path $GUARDIAN_DIR) {
    Write-Host "  Guardian directory already exists. Pulling latest..." -ForegroundColor DarkYellow
    Push-Location $GUARDIAN_DIR
    git pull origin $GUARDIAN_BRANCH 2>&1 | Out-Null
    Pop-Location
} else {
    git clone --depth 1 --branch $GUARDIAN_BRANCH $GUARDIAN_REPO $GUARDIAN_DIR
}
Write-Host "  Guardian cloned to: $GUARDIAN_DIR" -ForegroundColor Green

# --- Step 3: Configure Guardian .env ---
Write-Host "[3/6] Configuring Guardian environment..." -ForegroundColor Yellow

# Guardian expects these env vars in its .env or docker-compose
$guardianEnvPath = "$GUARDIAN_DIR\.env"

# Build the .env content for Guardian
$guardianEnv = @"
# Generated by Carbon Passport Platform setup script
# $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

GUARDIAN_ENV=develop

# Hedera Network
HEDERA_NET=$NETWORK
OPERATOR_ID=$OPERATOR_ID
OPERATOR_KEY=$OPERATOR_KEY

# Preused accounts (Guardian will create these on first run)
INITIALIZATION_TOPIC_ID=

# IPFS (Web3.Storage / NFT.Storage — optional for testnet)
IPFS_STORAGE_API_KEY=

# Filebase (S3-compatible IPFS pinning — optional)
FILEBASE_KEY=
FILEBASE_SECRET=
FILEBASE_BUCKET=

# Ports
GUARDIAN_PORT=3000
MQ_PORT=4222
DB_PORT=27017
CACHE_PORT=6379
"@

Set-Content -Path $guardianEnvPath -Value $guardianEnv -Encoding UTF8
Write-Host "  Guardian .env configured at: $guardianEnvPath" -ForegroundColor Green


# --- Step 4: Start Guardian via Docker Compose ---
Write-Host "[4/6] Starting Guardian services..." -ForegroundColor Yellow
Write-Host "  This may take 5-10 minutes on first run (downloading images)..." -ForegroundColor DarkYellow

Push-Location $GUARDIAN_DIR

# Find the docker-compose file
$composeFile = $null
if (Test-Path "docker-compose.yml") { $composeFile = "docker-compose.yml" }
elseif (Test-Path "deploy/docker-compose.yml") { $composeFile = "deploy/docker-compose.yml" }
else {
    Write-Error "Could not find docker-compose.yml in Guardian directory."
    Pop-Location
    exit 1
}

Write-Host "  Using compose file: $composeFile"

# Start all services
docker compose -f $composeFile --profile all up -d 2>&1

Pop-Location
Write-Host "  Guardian services starting..." -ForegroundColor Green

# --- Step 5: Wait for Guardian API to be ready ---
Write-Host "[5/6] Waiting for Guardian API to be ready..." -ForegroundColor Yellow
$maxWait = 180  # 3 minutes
$waited = 0
$guardianUrl = "http://localhost:3000/api/v1"

while ($waited -lt $maxWait) {
    try {
        $response = Invoke-WebRequest -Uri "$guardianUrl/accounts/session" -Method GET -TimeoutSec 5 -ErrorAction SilentlyContinue
        if ($response.StatusCode -eq 200 -or $response.StatusCode -eq 401) {
            Write-Host "  Guardian API is ready at $guardianUrl" -ForegroundColor Green
            break
        }
    } catch {
        # Not ready yet
    }
    Start-Sleep -Seconds 5
    $waited += 5
    Write-Host "  Waiting... ($waited/$maxWait seconds)" -ForegroundColor DarkGray
}

if ($waited -ge $maxWait) {
    Write-Warning "Guardian API did not respond within $maxWait seconds."
    Write-Warning "Check Docker logs: docker compose -f $composeFile logs -f guardian-service"
    Write-Warning "Guardian may still be initializing. Try again in a few minutes."
}

# --- Step 6: Create default users ---
Write-Host "[6/6] Creating default Guardian users..." -ForegroundColor Yellow

$headers = @{ "Content-Type" = "application/json" }

# Register Standard Registry
try {
    $srBody = @{ username = "StandardRegistry"; password = "test"; role = "STANDARD_REGISTRY" } | ConvertTo-Json
    $srRes = Invoke-RestMethod -Uri "$guardianUrl/accounts/register" -Method POST -Body $srBody -Headers $headers -ErrorAction SilentlyContinue
    Write-Host "  StandardRegistry user created." -ForegroundColor Green
} catch {
    Write-Host "  StandardRegistry user may already exist (OK)." -ForegroundColor DarkYellow
}

# Set SR Hedera credentials
try {
    # Login as SR first
    $loginBody = @{ username = "StandardRegistry"; password = "test" } | ConvertTo-Json
    $loginRes = Invoke-RestMethod -Uri "$guardianUrl/accounts/login" -Method POST -Body $loginBody -Headers $headers
    $srToken = $loginRes.accessToken
    if (!$srToken -and $loginRes.refreshToken) {
        $refreshBody = @{ refreshToken = $loginRes.refreshToken } | ConvertTo-Json
        $tokenRes = Invoke-RestMethod -Uri "$guardianUrl/accounts/access-token" -Method POST -Body $refreshBody -Headers $headers
        $srToken = $tokenRes.accessToken
    }

    if ($srToken) {
        $authHeaders = @{ "Content-Type" = "application/json"; "Authorization" = "Bearer $srToken" }
        # Set Hedera credentials for SR
        $credBody = @{
            operatorId = $OPERATOR_ID
            operatorKey = $OPERATOR_KEY
        } | ConvertTo-Json
        Invoke-RestMethod -Uri "$guardianUrl/profiles" -Method PUT -Body $credBody -Headers $authHeaders -ErrorAction SilentlyContinue
        Write-Host "  StandardRegistry Hedera credentials configured." -ForegroundColor Green
    }
} catch {
    Write-Host "  Could not configure SR credentials: $($_.Exception.Message)" -ForegroundColor DarkYellow
}

# Register VVB
try {
    $vvbBody = @{ username = "VVB"; password = "test"; role = "USER" } | ConvertTo-Json
    Invoke-RestMethod -Uri "$guardianUrl/accounts/register" -Method POST -Body $vvbBody -Headers $headers -ErrorAction SilentlyContinue
    Write-Host "  VVB user created." -ForegroundColor Green
} catch {
    Write-Host "  VVB user may already exist (OK)." -ForegroundColor DarkYellow
}

# Register ProjectProponent
try {
    $ppBody = @{ username = "ProjectProponent"; password = "test"; role = "USER" } | ConvertTo-Json
    Invoke-RestMethod -Uri "$guardianUrl/accounts/register" -Method POST -Body $ppBody -Headers $headers -ErrorAction SilentlyContinue
    Write-Host "  ProjectProponent user created." -ForegroundColor Green
} catch {
    Write-Host "  ProjectProponent user may already exist (OK)." -ForegroundColor DarkYellow
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host " Guardian Setup Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Guardian API : $guardianUrl" -ForegroundColor Cyan
Write-Host "  Guardian UI  : http://localhost:3000" -ForegroundColor Cyan
Write-Host "  Users        : StandardRegistry / VVB / ProjectProponent (password: test)" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Your platform is configured to connect automatically." -ForegroundColor White
Write-Host "  Start the platform: npx next dev --turbopack" -ForegroundColor White
Write-Host ""
Write-Host "  To stop Guardian: docker compose -f guardian/deploy/docker-compose.yml --profile all down" -ForegroundColor DarkGray
Write-Host "  To view logs:     docker compose -f guardian/deploy/docker-compose.yml logs -f" -ForegroundColor DarkGray
Write-Host ""
